# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name_plural': 'Paginas'},
        ),
    ]
