# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0002_auto_20160810_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={},
        ),
    ]
