# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0004_auto_20160810_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default='antes de update'),
            preserve_default=False,
        ),
    ]
