# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0006_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
