# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0007_auto_20160826_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('imagen', models.ImageField(default='imagenes_promociones/None/no-img.jpg', upload_to='imagenes_promociones/')),
                ('texto', models.TextField()),
            ],
        ),
    ]
