# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0008_promociones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('imagen', models.ImageField(default='imagenes_promociones/None/no-img.jpg', upload_to='imagenes_promociones/')),
                ('texto', models.TextField()),
                ('fecha', models.DateField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Promociones',
        ),
    ]
