# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0009_auto_20160830_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(default='imagenes_promociones/None/no-img.jpg', upload_to='borbolla_main/imagenes_promociones/'),
        ),
    ]
