# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0014_imagenesestaticas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesestaticas',
            name='texto1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagenesestaticas',
            name='texto2',
            field=models.TextField(max_length=200),
        ),
    ]
