# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0015_auto_20160831_0501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenesestaticas',
            options={'get_latest_by': 'fecha'},
        ),
    ]
