# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0016_auto_20160831_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('foto', models.ImageField(default='testimonios/None/no-img.jpg', upload_to='static/testimonios/')),
                ('cita', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenesEstaticas',
        ),
    ]
