# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0018_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(default='imagenes_promociones/None/no-img.jpg', upload_to='static/personas/'),
        ),
    ]
