# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0020_perfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='picture',
            new_name='foto',
        ),
    ]
