# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0021_auto_20160907_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=2)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=50)),
                ('celular', models.CharField(max_length=20)),
                ('enterado', models.CharField(max_length=2)),
                ('varioscursos', models.BooleanField()),
                ('variosfamiliares', models.BooleanField()),
            ],
        ),
    ]
