# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0022_academia'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
