# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borbolla_main', '0023_academia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='varioscursos',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='academia',
            name='variosfamiliares',
            field=models.NullBooleanField(),
        ),
    ]
